import type {HeroHotspot} from '@/lib/hero-hotspot-types';

/** Matches exported `hero-mobile.jpg` (from 1 (33).png). */
export const HERO_MOBILE_ASPECT = 864 / 1821;

export const heroMobileHotspots: HeroHotspot[] = [
  {
    id: 'cta-quote',
    labelKey: 'requestQuote',
    left: 4,
    top: 22.5,
    width: 92,
    height: 5.5,
    action: {type: 'quote'},
  },
  {
    id: 'cta-whatsapp',
    labelKey: 'chatWhatsApp',
    left: 4,
    top: 28.5,
    width: 92,
    height: 5.5,
    action: {type: 'whatsapp'},
  },
  {
    id: 'trust-quality',
    labelKey: 'trustQuality',
    left: 4,
    top: 35,
    width: 92,
    height: 6,
    action: {type: 'link', href: '/quality'},
  },
  {
    id: 'trust-countries',
    labelKey: 'trustCountries',
    left: 4,
    top: 41.5,
    width: 92,
    height: 6,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'trust-delivery',
    labelKey: 'trustDelivery',
    left: 4,
    top: 48,
    width: 92,
    height: 6,
    action: {type: 'link', href: '/packaging'},
  },
  {
    id: 'carousel-prev',
    labelKey: 'carouselPrev',
    left: 1,
    top: 56,
    width: 12,
    height: 14,
    action: {type: 'link', href: '/products'},
  },
  {
    id: 'carousel-products',
    labelKey: 'carouselProducts',
    left: 14,
    top: 55,
    width: 72,
    height: 16,
    action: {type: 'link', href: '/products'},
  },
  {
    id: 'carousel-next',
    labelKey: 'carouselNext',
    left: 87,
    top: 56,
    width: 12,
    height: 14,
    action: {type: 'link', href: '/products'},
  },
  {
    id: 'stat-countries',
    labelKey: 'statCountries',
    left: 2,
    top: 72.5,
    width: 23,
    height: 6,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'stat-volume',
    labelKey: 'statVolume',
    left: 26,
    top: 72.5,
    width: 23,
    height: 6,
    action: {type: 'link', href: '/about'},
  },
  {
    id: 'stat-quality',
    labelKey: 'statQuality',
    left: 50,
    top: 72.5,
    width: 23,
    height: 6,
    action: {type: 'link', href: '/quality'},
  },
  {
    id: 'stat-support',
    labelKey: 'statSupport',
    left: 74,
    top: 72.5,
    width: 23,
    height: 6,
    action: {type: 'link', href: '/contact'},
  },
  {
    id: 'bar-website',
    labelKey: 'barWebsite',
    left: 0,
    top: 93,
    width: 33,
    height: 7,
    action: {type: 'external', href: 'https://tatglcoltd.com'},
  },
  {
    id: 'bar-phone',
    labelKey: 'barPhone',
    left: 33,
    top: 93,
    width: 34,
    height: 7,
    action: {type: 'tel'},
  },
  {
    id: 'bar-whatsapp',
    labelKey: 'barWhatsApp',
    left: 67,
    top: 93,
    width: 33,
    height: 7,
    action: {type: 'whatsapp'},
  },
];
