import type {HeroHotspot} from '@/lib/hero-hotspot-types';

/** Matches exported `hero-desktop.jpg` (from 1 (29).png). */
export const HERO_DESKTOP_ASPECT = 1536 / 856;

export const heroDesktopHotspots: HeroHotspot[] = [
  {
    id: 'cta-quote',
    labelKey: 'requestQuote',
    left: 2.5,
    top: 36.5,
    width: 19,
    height: 6,
    action: {type: 'quote'},
  },
  {
    id: 'cta-products',
    labelKey: 'ourProducts',
    left: 22.5,
    top: 36.5,
    width: 17,
    height: 6,
    action: {type: 'link', href: '/products'},
  },
  {
    id: 'stat-countries',
    labelKey: 'statCountries',
    left: 2.5,
    top: 46,
    width: 9.5,
    height: 9,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'stat-volume',
    labelKey: 'statVolume',
    left: 12.5,
    top: 46,
    width: 9.5,
    height: 9,
    action: {type: 'link', href: '/about'},
  },
  {
    id: 'stat-quality',
    labelKey: 'statQuality',
    left: 22.5,
    top: 46,
    width: 9.5,
    height: 9,
    action: {type: 'link', href: '/quality'},
  },
  {
    id: 'stat-support',
    labelKey: 'statSupport',
    left: 32.5,
    top: 46,
    width: 9.5,
    height: 9,
    action: {type: 'link', href: '/contact'},
  },
  {
    id: 'tracking-details',
    labelKey: 'viewDetails',
    left: 76,
    top: 45.5,
    width: 12,
    height: 4,
    action: {type: 'link', href: '/packaging'},
  },
  {
    id: 'solution-bulk',
    labelKey: 'solutionBulk',
    left: 2,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/products'},
  },
  {
    id: 'solution-container',
    labelKey: 'solutionContainer',
    left: 11,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/packaging'},
  },
  {
    id: 'solution-inspection',
    labelKey: 'solutionInspection',
    left: 20,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/quality'},
  },
  {
    id: 'solution-shipping',
    labelKey: 'solutionShipping',
    left: 29,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'solution-customs',
    labelKey: 'solutionCustoms',
    left: 38,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/packaging'},
  },
  {
    id: 'solution-delivery',
    labelKey: 'solutionDelivery',
    left: 47,
    top: 81,
    width: 9,
    height: 12,
    action: {type: 'link', href: '/packaging'},
  },
  {
    id: 'dest-asia',
    labelKey: 'destAsia',
    left: 80,
    top: 70.5,
    width: 16,
    height: 4.5,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'dest-middle-east',
    labelKey: 'destMiddleEast',
    left: 80,
    top: 75.5,
    width: 16,
    height: 4.5,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'dest-africa',
    labelKey: 'destAfrica',
    left: 80,
    top: 80.5,
    width: 16,
    height: 4.5,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'dest-europe',
    labelKey: 'destEurope',
    left: 80,
    top: 85.5,
    width: 16,
    height: 4.5,
    action: {type: 'link', href: '/markets'},
  },
  {
    id: 'dest-north-america',
    labelKey: 'destNorthAmerica',
    left: 80,
    top: 90.5,
    width: 16,
    height: 4.5,
    action: {type: 'link', href: '/markets'},
  },
];
