/**
 * Auto-generated by scripts/deploy-brand-images.mjs — do not edit manually.
 * Slugs listed here have a dedicated WebP at public/images/products/{slug}.webp
 */
export const productImageSlugs = new Set<string>([
  "irri-6-long-grain-rice",
  "irri-9-long-grain-rice",
  "japonica-rice",
  "jasmine-rice-thai-hom-mali",
  "parboiled-rice-5-broken",
  "quality-brown-rice",
  "thai-brown-jasmine-rice",
  "thai-glutinous-rice",
  "thai-glutinous-rice-25-broken",
  "thai-hom-patum-rice",
  "thai-jasmine-black-cargo-rice",
  "thai-jasmine-red-cargo-rice",
  "thai-long-grain-rice",
  "thai-parboiled-rice",
  "thai-riceberry-rice",
  "thai-white-rice-10-broken",
  "thai-white-rice-100-broken",
  "thai-white-rice-100-sortexed",
  "thai-white-rice-25-broken",
  "white-rice-5-broken",
]);
