/**
 * Auto-generated by scripts/import-product-image.mjs — do not edit manually.
 * Slugs listed here have a dedicated WebP at public/images/products/{slug}.webp
 */
export const productImageSlugs = new Set<string>([
  "jasmine-rice-thai-hom-mali",
  "thai-long-grain-rice",
  "thai-parboiled-rice",
]);
